### ISSUE TITLE
Breaks desktop

### ISSUE THREAD

**Issue by jaredbm** [nepthar/particles.widget#1]
It seems to be breaking my desktop all of a sudden where all icons become unclickable. If I disable this widget they become clickable again.

**Comment by nepthar** [comment]
Since you're seeing this issue with another widget: https://github.com/roele/istats.widget/issues/43 , maybe it's more appropriate to file a ticket against https://github.com/felixhageloh/uebersicht.

Otherwise, mind digging in and posting a PR with what you find?

**Comment by jaredbm** [comment]
I think I fixed it now with disabling interaction. Not sure why that was turned on all of a sudden. Maybe with a recent update
