### ISSUE TITLE
No Particles Appearing

### ISSUE THREAD

**Issue by CrumplesHQ** [nepthar/particles.widget#3]
Hello, I'm seeming to have an issue with the Particles Widget, I put the folder into my Widgets folder and reloaded all of them but nothing seems to be happening. Do I need to edit something in the .coffee file? Does it also matter if I have a plain black wallpaper/background?

**Comment by nepthar** [comment]
Ah shit I probably broke something on my most recent update. It should "just work" as soon as you install it.

I'm looking into it now. I appreciate the report.

**Comment by nepthar** [comment]
Okay, give it another try with the updated zip file. It seems to work on my machine. Here's what I did:
1. Download the zip file from this repo (particles.widget.zip)
2. Unzip it
3. Click on Ubersicht  on the menu bar > "Open Widgets Folder"
4. Copy the unzipped particles.widget folder into there

Let me know how it goes

**Comment by nepthar** [comment]
@Crumpless I'm pretty sure this is fixed. If I don't hear back from you in a day or so I'm going to close the issue.
