### ISSUE TITLE
Black bar when menubar not hidden on Mojave (2021 MBP with notch)

### ISSUE THREAD

**Issue by Nykx** [nepthar/particles.widget#4]
When the menubar is not hidden there is a black bar between it and the main portion of the desktop. This is fixed by updating line 65 in particles.coffee with "border: 0px" from 2px. There does not seem to be any negative impacts of this change (even when menubar is hidden).

I do not know if this would negatively impact other systems/implications, but it was a fix that remedied my particular issue.

Mostly just an FYI. Thanks for your work!

**Comment by nepthar** [comment]
Hi Nykx, thanks so much for the report! Do feel comfortable making a PR for this change? If so you'll "get credit" for it here on Github. If not, I'm happy to make it on your behalf. Glad you appreciate it!

**Comment by Nykx** [comment]
I just submitted a PR. My first one so hopefully I did everything OK! Thanks for the opportunity to learn :)

**Comment by nepthar** [comment]
Fixed in #7
